// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model/UserInfo.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 1418540786761791815),
      name: 'UserInfo',
      lastPropertyId: const IdUid(4, 4605830529299355368),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4441657152874120124),
            name: 'cardNumber',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(2, 6369254145463365868),
            name: 'address',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 7464784075761128709),
            name: 'userName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 4605830529299355368),
            name: 'id',
            type: 6,
            flags: 1)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 1418540786761791815),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    UserInfo: EntityDefinition<UserInfo>(
        model: _entities[0],
        toOneRelations: (UserInfo object) => [],
        toManyRelations: (UserInfo object) => {},
        getId: (UserInfo object) => object.id,
        setId: (UserInfo object, int id) {
          object.id = id;
        },
        objectToFB: (UserInfo object, fb.Builder fbb) {
          final cardNumberOffset = fbb.writeString(object.cardNumber);
          final addressOffset = fbb.writeString(object.address);
          final userNameOffset = fbb.writeString(object.userName);
          fbb.startTable(5);
          fbb.addOffset(0, cardNumberOffset);
          fbb.addOffset(1, addressOffset);
          fbb.addOffset(2, userNameOffset);
          fbb.addInt64(3, object.id);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = UserInfo(
              cardNumber: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 4, ''),
              address: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              userName: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [UserInfo] entity fields to define ObjectBox queries.
class UserInfo_ {
  /// see [UserInfo.cardNumber]
  static final cardNumber =
      QueryStringProperty<UserInfo>(_entities[0].properties[0]);

  /// see [UserInfo.address]
  static final address =
      QueryStringProperty<UserInfo>(_entities[0].properties[1]);

  /// see [UserInfo.userName]
  static final userName =
      QueryStringProperty<UserInfo>(_entities[0].properties[2]);

  /// see [UserInfo.id]
  static final id = QueryIntegerProperty<UserInfo>(_entities[0].properties[3]);
}
